import React from "react";

const services = [
  { number: "01", title: "Anxiety & Panic Therapy", text: "Create more steadiness when worry, physical tension, panic, or constant overthinking starts to take over. We work at a practical pace while exploring what is underneath the symptoms." },
  { number: "02", title: "Trauma & EMDR", text: "Process the impact of single-incident or long-standing trauma with an approach centered on safety, stabilization, regulation, and carefully paced deeper work." },
  { number: "03", title: "Burnout & Perfectionism", text: "Step out of cycles of high internal pressure and pushing through. Therapy can become a place to reconnect with yourself and develop more sustainable ways of living and working." }
];

const faqs = [
  { q: "Do you offer in-person and online therapy?", a: "Yes. Dr. Maya Reynolds offers in-person therapy from her Santa Monica office and secure telehealth sessions for clients located in California." },
  { q: "Who do you work with?", a: "The practice focuses on adults, particularly people experiencing anxiety, panic, trauma, burnout, perfectionism, or the effects of earlier life experiences." },
  { q: "What approaches do you use?", a: "Dr. Reynolds integrates evidence-based methods including cognitive-behavioral therapy (CBT), EMDR, mindfulness-based practices, and body-oriented techniques." },
  { q: "What is trauma therapy like?", a: "Trauma work is paced carefully, with an emphasis on safety and stabilization. The goal is to help clients feel more regulated in daily life while making space to understand and process what they have experienced." },
  { q: "What can I expect from the therapy relationship?", a: "The approach is warm, collaborative, and grounded. Sessions are structured enough to feel supportive while leaving room for reflection and depth, with clients actively involved in the process." }
];
function Arrow(){ return <span aria-hidden="true">↗</span>; }

export default function Home(){ return (
<main>
<header className="absolute inset-x-0 top-0 z-30 text-white"><div className="container-wide flex items-center justify-between py-7"><a href="#" className="leading-none"><span className="block text-[11px] uppercase tracking-[.28em]">Dr. Maya Reynolds</span><span className="serif mt-1 block text-2xl">Clinical Psychology</span></a><nav className="hidden items-center gap-8 text-sm md:flex"><a className="nav-link" href="#about">About</a><a className="nav-link" href="#services">Services</a><a className="nav-link" href="#office">Our Office</a><a className="nav-link" href="#faq">FAQs</a></nav><a href="#contact" className="rounded-full border border-white/60 px-5 py-3 text-xs font-semibold uppercase tracking-[.16em] transition hover:bg-white hover:text-ink">Get Started</a></div></header>
<section className="relative min-h-[760px] overflow-hidden bg-ink text-white"><img className="absolute inset-0 image-cover opacity-55" src="https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=2200&q=85" alt=""/><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(25,39,44,.88),rgba(25,39,44,.48),rgba(25,39,44,.25))]"/><div className="relative container-wide flex min-h-[760px] items-center pb-20 pt-32"><div className="max-w-3xl"><p className="mb-6 text-xs font-semibold uppercase tracking-[.3em] text-[#d8e5da]">In-person in Santa Monica · Online across California</p><h1 className="serif max-w-3xl text-6xl leading-[.94] sm:text-7xl lg:text-[92px]">A quieter place to understand what you’re carrying.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-white/85">Warm, collaborative therapy for adults navigating anxiety, trauma, panic, burnout, and the pressure to keep everything together.</p><div className="mt-9 flex flex-wrap gap-4"><a href="#contact" className="rounded-full bg-white px-7 py-4 text-sm font-semibold text-ink transition hover:bg-sand">Schedule a consultation <Arrow/></a><a href="#about" className="rounded-full border border-white/50 px-7 py-4 text-sm font-semibold transition hover:bg-white/10">Learn about my approach</a></div></div></div></section>
<section id="about" className="noise section-pad"><div className="container-wide grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative mx-auto w-full max-w-[480px]"><div className="absolute -bottom-5 -left-5 h-32 w-32 rounded-full bg-mist"/><div className="relative aspect-[4/5] overflow-hidden rounded-[180px_180px_18px_18px]"><img className="image-cover" src="https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=1100&q=85" alt="Calm professional workspace"/></div><div className="absolute -right-5 bottom-8 rounded-2xl bg-white px-6 py-5 shadow-soft"><p className="text-xs uppercase tracking-[.18em] text-sage-dark">A grounded approach</p><p className="serif mt-1 text-2xl">Warm · Collaborative · Evidence-based</p></div></div><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-sage-dark">About Dr. Maya Reynolds, PsyD</p><h2 className="serif mt-5 max-w-2xl text-5xl leading-tight sm:text-6xl">You can look functional and still feel exhausted inside.</h2><div className="mt-7 space-y-5 text-[17px] leading-8 text-ink/75"><p>I’m a licensed clinical psychologist based in Santa Monica, California, offering therapy for adults who feel overwhelmed by anxiety, stress, or the lingering effects of past experiences.</p><p>Many of the people I work with are high-achieving, thoughtful, and self-aware—but internally feel exhausted, stuck in overthinking, or emotionally on edge.</p><p>My work combines practical tools with depth-oriented work, integrating CBT, EMDR, mindfulness-based practices, and body-oriented techniques.</p></div><a href="#contact" className="mt-8 inline-flex items-center gap-2 border-b border-ink pb-2 text-sm font-semibold">Begin with a conversation <Arrow/></a></div></div></section>
<section className="bg-sage text-white"><div className="container-wide section-pad grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-white/70">Who I work with</p><h2 className="serif mt-4 text-5xl leading-tight">For adults carrying a lot, quietly.</h2></div><div className="grid gap-4 sm:grid-cols-2">{[["High-achieving adults","Thoughtful, capable people who feel stretched thin, overwhelmed, or disconnected from themselves."],["Professionals & entrepreneurs","People navigating burnout, perfectionism, and the pressure of a fast-paced working life."],["People healing from trauma","Adults working through single-incident trauma or complex, long-standing patterns from earlier experiences."],["People living with anxiety","Clients experiencing worry, panic, physical tension, sleep difficulties, or a constant sense of being on edge."]].map(([title,text])=><div key={title} className="rounded-3xl border border-white/20 p-7"><h3 className="serif text-3xl">{title}</h3><p className="mt-3 leading-7 text-white/75">{text}</p></div>)}</div></div></section>
<section id="services" className="section-pad bg-cream"><div className="container-wide"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-sage-dark">Areas of support</p><h2 className="serif mt-4 text-5xl leading-tight sm:text-6xl">Therapy that meets the whole experience.</h2><p className="mt-5 text-lg leading-8 text-ink/70">Emotional patterns are connected to what we think, feel, remember, and experience in our bodies. Our work makes room for all of it.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{services.map((service)=><article key={service.number} className="reveal-card rounded-[28px] bg-white p-8 shadow-[0_10px_40px_rgba(36,51,59,.05)]"><div className="flex items-center justify-between"><span className="text-xs font-semibold tracking-[.2em] text-sage-dark">{service.number}</span><span className="text-xl text-clay">↗</span></div><h3 className="serif mt-14 text-4xl leading-tight">{service.title}</h3><p className="mt-5 leading-7 text-ink/65">{service.text}</p><a href="#contact" className="mt-8 inline-block text-sm font-semibold">Learn more ↗</a></article>)}</div></div></section>
<section className="section-pad bg-mist"><div className="container-wide grid overflow-hidden rounded-[36px] bg-white lg:grid-cols-2"><div className="min-h-[520px] bg-[linear-gradient(140deg,#dbe6de,#f7f3ec)] p-10 sm:p-14"><p className="text-xs font-semibold uppercase tracking-[.25em] text-sage-dark">A thoughtful pace</p><div className="mt-20 max-w-sm"><p className="serif text-5xl leading-tight">Therapy can be both practical and deeply human.</p></div></div><div className="flex items-center px-7 py-20 sm:px-14 lg:px-20"><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-sage-dark">How we work</p><h2 className="serif mt-5 text-5xl leading-tight sm:text-6xl">Practical enough to use. Deep enough to matter.</h2><div className="mt-7 space-y-5 text-[17px] leading-8 text-ink/75"><p>Sessions are structured enough to feel supportive while still leaving space for reflection and depth.</p><p>We may use CBT to understand patterns, EMDR to process trauma, mindfulness to build awareness, and body-oriented techniques to notice the physiological side of what you’re experiencing.</p><p>Trauma work is paced carefully, with an emphasis on safety, stabilization, and helping you feel more regulated in daily life—not just during sessions.</p></div></div></div></div></section>
<section id="office" className="section-pad bg-white"><div className="container-wide"><div className="mx-auto max-w-3xl text-center"><p className="text-xs font-semibold uppercase tracking-[.25em] text-sage-dark">New · Our Office</p><h2 className="serif mt-4 text-5xl leading-tight sm:text-6xl">A calm space to slow down.</h2><p className="mt-5 text-lg leading-8 text-ink/70">My Santa Monica office is designed to feel quiet, private, and grounding, with natural light and a comfortable, uncluttered environment. The space itself can offer a softer transition into the work of therapy.</p></div><div className="mt-12 grid gap-5 md:grid-cols-[1.25fr_.75fr] md:grid-rows-2"><div className="row-span-2 min-h-[520px] overflow-hidden rounded-[32px]"><img className="image-cover" src="/office1.jpeg" alt="Bright, uncluttered therapy-style interior"/></div><div className="min-h-[250px] overflow-hidden rounded-[32px]"><img className="image-cover" src="/office2.jpeg" alt="Warm neutral interior with natural light"/></div><div className="flex min-h-[250px] items-end rounded-[32px] bg-mist p-8"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-sage-dark">Santa Monica, California</p><h3 className="serif mt-2 text-3xl">Private. Comfortable. Grounding.</h3><p className="mt-3 text-sm leading-6 text-ink/65">In-person sessions are available from the Santa Monica office, with secure telehealth available across California.</p></div></div></div><p className="mt-5 text-center text-xs text-ink/45">Office photography supplied for Dr. Maya Reynolds’s profile.</p></div></section>
<section id="faq" className="section-pad bg-cream"><div className="container-wide grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-sage-dark">FAQs</p><h2 className="serif mt-4 text-5xl leading-tight">A few things you may be wondering.</h2><p className="mt-5 leading-7 text-ink/65">If your question isn’t answered here, a consultation can be a simple place to start.</p></div><div className="faq divide-y divide-ink/10 border-y border-ink/10">{faqs.map((faq)=><details key={faq.q} className="py-6"><summary className="flex items-center justify-between gap-5 text-lg font-medium"><span>{faq.q}</span><span className="plus text-2xl font-light">+</span></summary><p className="max-w-2xl pt-4 leading-7 text-ink/65">{faq.a}</p></details>)}</div></div></section>
<section id="contact" className="relative overflow-hidden bg-ink text-white"><div className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-sage/30 blur-2xl"/><div className="container-wide section-pad relative"><div className="grid gap-12 lg:grid-cols-[1fr_auto] lg:items-end"><div className="max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[.25em] text-[#cbdacb]">Start here</p><h2 className="serif mt-4 text-6xl leading-none sm:text-7xl">You don’t have to keep pushing through alone.</h2><p className="mt-7 max-w-xl text-lg leading-8 text-white/70">If you’re looking for a therapist who combines practical tools with depth-oriented work, I invite you to reach out and begin a conversation.</p></div><a href="mailto:hello@mayareynoldspsych.com" className="inline-flex w-fit rounded-full bg-white px-8 py-4 text-sm font-semibold text-ink transition hover:bg-sand">Request a consultation <span className="ml-2">↗</span></a></div><div className="mt-20 grid gap-8 border-t border-white/15 pt-8 text-sm text-white/65 sm:grid-cols-3"><div><p className="font-semibold text-white">Dr. Maya Reynolds, PsyD</p><p className="mt-2">Licensed Clinical Psychologist</p></div><div><p className="font-semibold text-white">Office</p><p className="mt-2">123th Street 45 W<br/>Santa Monica, CA 90401</p></div><div><p className="font-semibold text-white">Availability</p><p className="mt-2">In-person in Santa Monica<br/>Secure telehealth across California</p></div></div></div></section>
<footer className="bg-[#1d2a2f] py-7 text-center text-xs text-white/45"><div className="container-wide flex flex-col justify-between gap-3 sm:flex-row"><span>© 2026 Dr. Maya Reynolds, PsyD</span><span>Santa Monica · California</span></div></footer>
</main>); }